"""initial schema

Revision ID: 8332bd9be143
Revises: 
Created: 2026-09-08 07:23:17.817174+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# Custom column types referenced by autogenerated migrations.
import stockgame.server.db.base


revision = '8332bd9be143'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('started_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('ends_at', stockgame.server.db.base.UTCDateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('number', name=op.f('uq_seasons_number'))
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('prev_close_cents', sa.Integer(), nullable=False),
    sa.Column('open_cents', sa.Integer(), nullable=False),
    sa.Column('day_high_cents', sa.Integer(), nullable=False),
    sa.Column('day_low_cents', sa.Integer(), nullable=False),
    sa.Column('day_volume', sa.Integer(), nullable=False),
    sa.Column('shares_outstanding', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('drift', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=False),
    sa.Column('mean_reversion', sa.Float(), nullable=False),
    sa.Column('fair_value_cents', sa.Integer(), nullable=False),
    sa.Column('event_impact', sa.Float(), nullable=False),
    sa.Column('is_halted', sa.Boolean(), nullable=False),
    sa.Column('listed_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    sa.UniqueConstraint('symbol', name=op.f('uq_stocks_symbol'))
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_sector'), ['sector'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('username_lower', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('last_login_at', stockgame.server.db.base.UTCDateTime(), nullable=True),
    sa.Column('token_epoch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username_lower', name=op.f('uq_users_username_lower'))
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('unlocked_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('user_id', 'code', name='uq_achievement')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('leaderboard_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=12), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('value_cents', sa.Integer(), nullable=False),
    sa.Column('pl_cents', sa.Integer(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('computed_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_leaderboard_entries_season_id_seasons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leaderboard_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaderboard_entries')),
    sa.UniqueConstraint('period', 'season_id', 'user_id', name='uq_leaderboard_row')
    )
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.create_index('ix_leaderboard_period_rank', ['period', 'rank'], unique=False)

    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=12), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=6), nullable=True),
    sa.Column('sector', sa.String(length=32), nullable=True),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_market_events_stock_id_stocks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_events'))
    )
    with op.batch_alter_table('market_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_events_created_at'), ['created_at'], unique=False)

    op.create_table('market_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('regime', sa.String(length=10), nullable=False),
    sa.Column('regime_ticks_left', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('day_started_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.Column('candle_ticks', sa.Integer(), nullable=False),
    sa.Column('index_value', sa.Integer(), nullable=False),
    sa.Column('index_open_cents', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('updated_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_market_state_season_id_seasons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_state'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=22), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=12), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price_cents', sa.Integer(), nullable=True),
    sa.Column('avg_fill_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.String(length=120), nullable=True),
    sa.Column('reserved_cash_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('expires_day', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_orders_stock_id_stocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('public_id', name=op.f('uq_orders_public_id'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_open', ['status', 'stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('value_cents', sa.Integer(), nullable=False),
    sa.Column('cash_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolio_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots')),
    sa.UniqueConstraint('user_id', 'day_index', name='uq_snapshot_day')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_user_day', ['user_id', 'day_index'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_cents', sa.Integer(), nullable=False),
    sa.Column('deposited_cents', sa.Integer(), nullable=False),
    sa.Column('realized_pl_cents', sa.Integer(), nullable=False),
    sa.Column('last_value_cents', sa.Integer(), nullable=False),
    sa.Column('day_open_value_cents', sa.Integer(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('best_trade_cents', sa.Integer(), nullable=False),
    sa.Column('worst_trade_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.CheckConstraint('cash_cents >= 0', name=op.f('ck_portfolios_cash_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('user_id', name=op.f('uq_portfolios_user_id'))
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=2), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('ts', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('open_cents', sa.Integer(), nullable=False),
    sa.Column('high_cents', sa.Integer(), nullable=False),
    sa.Column('low_cents', sa.Integer(), nullable=False),
    sa.Column('close_cents', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_price_history_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_lookup', ['stock_id', 'interval', 'ts'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('expires_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('client_info', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_watchlist_items_stock_id_stocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlist_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('user_id', 'stock_id', name='uq_watchlist_item')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_basis_cents', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('first_bought_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_holdings_quantity_non_negative')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_holdings_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_holdings_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings')),
    sa.UniqueConstraint('portfolio_id', 'stock_id', name='uq_holding')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=22), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=False),
    sa.Column('realized_pl_cents', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('created_at', stockgame.server.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_trades_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_trades_stock_id_stocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trades_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('public_id', name=op.f('uq_trades_public_id'))
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_stock_id'))
        batch_op.drop_index(batch_op.f('ix_trades_order_id'))
        batch_op.drop_index(batch_op.f('ix_trades_created_at'))

    op.drop_table('trades')
    op.drop_table('holdings')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_lookup')

    op.drop_table('price_history')
    op.drop_table('portfolios')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_user_day')

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_stock_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index('ix_orders_open')

    op.drop_table('orders')
    op.drop_table('market_state')
    with op.batch_alter_table('market_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_events_created_at'))

    op.drop_table('market_events')
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_leaderboard_period_rank')

    op.drop_table('leaderboard_entries')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_user_id'))

    op.drop_table('achievements')
    op.drop_table('users')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_sector'))

    op.drop_table('stocks')
    op.drop_table('seasons')
    # ### end Alembic commands ###
